### ISSUE TITLE
Fixed swift 3 warnings

### ISSUE THREAD

**Issue by starlight173** [HsoiEnterprises/HEAnalytics#29]
Xcode 7.3 has been released with some warning issues. Could you fix that? Thanks so much.

**Comment by hsoi** [comment]
I will eventually get to Swift 2.2 issues, but do not have the spare cycles right now (no promises as to when).

If you need the fixes sooner, you're welcome to issue a pull request.

**Comment by hsoi** [comment]
This should be resolved in https://github.com/HsoiEnterprises/HEAnalytics/releases/tag/v0.5.2
